HW locators
SevilAlekperova/TAF1 pull request #2
Opened 2022-10-10 15:53 UTC by SevilAlekperova

2022-10-16 18:51 UTC, wildpioneer requested changes

2022-10-16 18:51 UTC, wildpioneer commented on src/test/java/tests/SmokeTest2.java
>      public void validateSKFTest() throws InterruptedException {
??? Почему это в домашке по локаторам?

2022-10-18 11:17 UTC, SevilAlekperova commented
исправила, посмотри, пожалуйста

2022-10-30 11:24 UTC, wildpioneer commented
Проверено

2022-10-30 11:24 UTC, closed without merging